#!/usr/bin/env python3

# (c) Robin Humble. Wed Sep 25 18:58:22 AEST 2019
# licensed under the GPLv3

# showbf
#  - find slurm back-fill windows
#  - modeled after the maui/moab tool of the same name
#
# use pyslurm to look at all slurm jobs, reservations, and nodes, to see what
# slurm is using now (cores, gpus, mem, tmp disk) and what it has tentatively
# scheduled for the future.
# this tells us what (cores, mem, tmp) backfill windows remain for us to use 'now'.
#
# we don't attempt to find backfill windows for gpu jobs.
#
#  this code can also be run as 'qinfo' and 'spart'
#  - qinfo shows overall queue/partition resource availability, as well as
#      offline or blocked cores/nodes etc.
#  - spart is a kinda a combined qinfo and showbf
#
# each of the 3 modes of operation has various command line flags.
# see -h in each mode for details.

import pyslurm
import sys
import time
import datetime
import math

# configure the below for your cluster

# NOTE: gpu partitions are assumed to have 'gpu' in their name

# NOTE: only partitions in ppp, cpu_ppp will be printed

# NOTE: trevor is an example of a simple cpu-only queue

# NOTE: milan/milan-c/milan-gpu is an example of a more complicated queue with overlapping partitions and some cpu, some gpu nodes
#        there is also a hack in the code for milan things. this is deliberately
#        left as an example of how to combine two cpu queues into one before printing.

# partitions and their node name prefixes
#  eg. a skylake partition could contain john[1-100],bryan[1-8] nodes and would be 'skylake':['john','bryan']
#  partitions may overlap. eg. milan-c and milan-gpu overlap on the same nodes.
partitions = {'sstar':['sstar'], 'gstar':['gstar'], 'milan':['dave'], 'milan-c':['gina'], 'milan-gpu':['gina'], 'trevor':['trevor']}

# lower limit of the cores reserved for GPU jobs in each partition. cpu-only partitions are 0
partitionResGpuCores = {'sstar':0, 'gstar':0, 'milan':0, 'milan-c':16, 'milan-gpu':16, 'trevor':0}

# max cores usable by CPU jobs in each partitions. usually just the number of real cores.
# but can be limited by eg. MaxCPUsPerNode=48 or similar.
# different generations of nodes can have different numbers of cores within one partition
partitionMaxCpuCores = {'sstar':[32,16], 'gstar':[32,12], 'milan':[64], 'milan-c':[48], 'milan-gpu':[16], 'trevor':[12]}

# SMT/hyperthread threads per core. if not specified, then 1 is the default and means SMT/HT is off. can be 2 for many chips, or 4 for KNL.
partitionThreadsPerCore = {}

# arbitrary thresholds for what constitutes a low mem per core, or low local disk per core situation. in MB
partitionLowMem  = {'sstar':1000, 'gstar':1000, 'milan':1000, 'milan-c':1000, 'milan-gpu':1000, 'trevor':500}   # MB per core
partitionLowDisk = {'sstar':3000, 'gstar':3000, 'milan':3000, 'milan-c':3000, 'milan-gpu':3000, 'trevor':3000}  #  ""

# compact version of node names. used for the nodes lists in verbose views
compactPrefixes = {'bryan':'b', 'gina':'g', 'john':'j', 'sstar':'ss', 'gstar':'gs', 'dave':'d', 'trevor':'t'}

# output will be printed in the order of the fields in ppp, cpu_ppp. aka 'pretty print partitions'
# ppp is used by qinfo and spart and includes gpu partitions
ppp = [ "milan", "milan-gpu", "trevor" ]
# cpu_ppp is cpu-only partitions. used for showbf
cpu_ppp = [ "milan", "trevor" ]

# max allowed walltime for jobs. in seconds. eg. MaxTime=168:00:00
TMAX = 24*7*3600

debug = 0

def nodes():
    pyslurm_nodes = pyslurm.node().get()

    nodes = {}

    for host, n in pyslurm_nodes.items():
        nodes[host] = {}

        nodes[host]['state'] = n['state']

        nodes[host]['nCpus'] = n['cpus']
        nodes[host]['nCpusUsed'] = n['alloc_cpus']

        # track mem so can flag low mem
        nodes[host]['allocMem'] = n['alloc_mem']
        nodes[host]['realMem'] = n['real_memory']

        # track disk so can flag low disk
        nodes[host]['allocDisk'] = 0
        if 'tmp_disk' in n:
            # have local disks, and slurm is tracking the tmp gres
            nodes[host]['realDisk'] = n['tmp_disk']   # in MB
            for j in n['gres_used']:
                k = j.split(':')
                if k[0] == 'tmp':
                    nodes[host]['allocDisk'] = int(int(k[1])/(1024*1024))   # in MB
        else:
            # don't have local disks on nodes?
            nodes[host]['realDisk'] = 99999999999   # make it something large

        nodes[host]['nGpus'] = 0
        for gres in n['gres']:
            # eg. slurm 17/18: gpu:p100:2
            #              19: gpu:p100:2(S:0-1)
            g = gres.split(':')
            if (g[0] == 'gpu'):
                if len(g) == 2:
                   c = 0
                else:
                   c = int(g[2].split('(')[0])
                nodes[host]['nGpus'] += c

        nodes[host]['nGpusUsed'] = 0
        for gres in n['gres_used']:
            g = gres.split(':')
            if (g[0] == 'gpu'):   # eg. gpu:p100:0(IDX:N/A), gpu:p100:1(IDX:0), gpu:p100:2(IDX:0-1), gpu:c2050:0  (down)
                 if 'IDX' in g[-2]:
                     nodes[host]['nGpusUsed'] += int(g[-2].split('(')[0])

        nodes[host]['avail'] = True
        for d in [ 'DOWN', 'DRAIN', 'UNKNOWN', 'RESERVED' ]:
            if d in nodes[host]['state']:
                nodes[host]['avail'] = False

        # cores for each type of job
        nodes[host]['gpuLayout'] = []
        nodes[host]['cpuLayout'] = []
        nodes[host]['gpuJobCnt'] = 0
        nodes[host]['cpuJobCnt'] = 0

        nodes[host]['features'] = n['features']
        nodes[host]['futureJobs'] = []

    return nodes


def jobs():
    slurm_jobs = pyslurm.Jobs.load()

    j = {}

    for id, s in slurm_jobs.items():

        #print(id,s)
        j[id] = { 'nCpus':      s.cpus,
                  'state':      s.state,
                  'layout':     s.get_resource_layout_per_node(),
                  'timeLimit':  s.time_limit,  # minutes
                  'schedNodes': s.scheduled_nodes, # None or eg. bryan[1-4,6-8],john[1-3]
                  'startTime':  s.start_time,  # 0 or seconds
                }

        # pyslurm 24 has gres in layout
        #   eg. {'gina8': {'cpu_ids': '38', 'gres': {'gpu:a100': {'count': 1, 'indexes': '3'}, 'tmp:CNT': 21474836480}, 'memory': 10240}}
        j[id]['nGpus'] = 0
        for n, l in j[id]['layout'].items():  # loop over nodes
            if 'gres' in l:
                for g, d in l['gres'].items():  # loop over gres
                    if g[:3] == 'gpu':
                        j[id]['nGpus'] += l['gres'][g]['count']

    return j


def isFixedWidth(c):
   # return 0 if floating, otherwise the field width
   a = 0
   for j in c.split(','):
      for l in j.split('-'):  # eg. 011
         if len(l) != len('%d' % int(l)):
            return len(l)
   return a

# parse eg. "1,3,4-8,10-20,25" or "011-058"
def parseCpuList( cpus ):
    c = []
    for i in cpus.split(','):
        ss = i.split('-')
        if len(ss) > 1:  # found a range
            for j in range(int(ss[0]), int(ss[1])+1):
                c.append(j)
        else:            # found a single
            if i[0] != '.':  # found a , "..." sigh
               c.append(int(i))
    return c

def expandSlurmNodeList( nl ):
    # eg. john[4-6,9,23-27],bryan7
    #     gstar[011-058]
    hl = []
    # split on commas, and then fixup
    snl = []
    a = ''
    for h in nl.split(','):  # eg. john[4-6 9 23-27] bryan7
        if h[0].isdigit():
            a += ',' + h
        else:
            if a != '':
               snl.append(a)
            a = h
    snl.append(a)
    # expand the ranges
    for h in snl: # eg. john[4-6,9,23-27] bryan7
        if '[' not in h:
            hl.append(h)
            continue
        pre = h.split('[')[0]
        c = h.split('[')[1].split(']')[0]   # eg. 4-6,9 or 011-058
        # work out if it's fixed width fields or floating
        fw = isFixedWidth(c)
        for i in parseCpuList(c):
           if not fw:
              hl.append(pre + '%d' % i)
           else:
              hl.append(pre + str(i).rjust(fw, '0'))
    return hl


def reservations():
    a = pyslurm.reservation()
    res_dict = a.get()
    resnodes={}
    # for the purposes of backfill, we're only interested in the next res on a node, and don't care if it's whole node or 1 core.
    # this will be incorrect for currently active res's that aren't whole node.
    for r, v in res_dict.items():
        if 'node_list' in v.keys() and v['node_list'] != None:
            for n in expandSlurmNodeList(v['node_list']):
                if n in resnodes.keys():
                    tprev = resnodes[n]
                    if v['start_time'] < tprev:
                        resnodes[n] = v['start_time']
                else:
                    resnodes[n] = v['start_time']
    #print('resnodes.keys()', resnodes.keys())
    #print('resnodes', resnodes)
    return resnodes


def do_all():
    data = {}
    data['nodes'] = nodes()
    data['jobs'] = jobs()
    data['res'] = reservations()

    return data


class bins:
    def __init__(self):
       self.data = {}
       self.keycache = []

    def add(self, k, m=0, d=0, t=None, node=None):
       if t != None and t - time.time() < 0:  # time is -ve. reservation started some time in the past. can't use this bin
          return
       if k not in self.keycache:
          self.data[k] = {'cnt':1, 'mem':[m], 'disk':[d], 'time':[t], 'nodes':[node]}
          self.keycache = self.data.keys()
       else:
          self.data[k]['cnt'] += 1
          self.data[k]['mem'].append(m)
          self.data[k]['disk'].append(d)
          self.data[k]['time'].append(t)
          self.data[k]['nodes'].append(node)

    def extend(self, b):
       """append bins object 'b' to this object"""
       for k in b.bins():
          if k not in self.keycache:
             self.data[k] = b.data[k]
             self.keycache = self.data.keys()
          else:
             self.data[k]['cnt'] += b.data[k]['cnt']
             self.data[k]['mem'].extend(b.data[k]['mem'])
             self.data[k]['disk'].extend(b.data[k]['disk'])
             self.data[k]['time'].extend(b.data[k]['time'])
             self.data[k]['nodes'].extend(b.data[k]['nodes'])

    def bins(self):
       return self.keycache

    def cnt(self, i):
       return self.data[i]['cnt']

    def mems(self, i):
       return self.data[i]['mem']

    def disks(self, i):
       return self.data[i]['disk']

    def nodes(self, i):
       return self.data[i]['nodes']

    def memsAve(self, i):
       d = self.data[i]['mem']
       return sum(d)/len(d)

    def memsMedian(self, i):
       d = self.data[i]['mem']
       d.sort()
       return d[int(len(d)/2)]

    def memsMin(self, i):
       d = self.data[i]['mem']
       d.sort()
       return d[0]

    def memsMax(self, i):
       d = self.data[i]['mem']
       d.sort()
       return d[-1]

    def disksAve(self, i):
       d = self.data[i]['disk']
       return sum(d)/len(d)

    def disksMedian(self, i):
       d = self.data[i]['disk']
       d.sort()
       return d[int(len(d)/2)]

    def disksMin(self, i):
       d = self.data[i]['disk']
       d.sort()
       return d[0]

    def disksMax(self, i):
       d = self.data[i]['disk']
       d.sort()
       return d[-1]

    def timesMin(self, i):
       d = self.data[i]['time']
       d = [x for x in d if x is not None]
       if len(d) == 0:
           return None   # all None => Inf time
       d.sort()
       return d[0]

    def timesMax(self, i):
       d = self.data[i]['time']
       dn = [x for x in d if x is None]
       if len(dn) != 0:
           return None   # some None's => Inf time
       d = [x for x in d if x is not None]
       d.sort()
       return d[-1]

    def sum(self):
       s = 0
       for i, j in self.data.items():
           s += i*j['cnt']
       return s


def minFutureJobTime(node, jobs, hn, res):
    st = None
    # future jobs
    for id in node['futureJobs']:
        t = jobs[id]['startTime']
        if st == None:
            st = t
        else:
            st = min(st, t)
    # next or current res
    if hn in res.keys():
        t = res[hn]
        if st == None:
           st = t
        else:
           st = min(st, t)
    #print('j in', st - time.time(), 'is', jobs[id])
    return st

def get_core_usage(data):
    """
      returns
          u == usage by partition
        bcu == binned core (and gpu) usage for each partion
    """
    # split gpu cores from cpu cores
    for id, job in data['jobs'].items():
        if job['state'] == 'RUNNING':
            for n, l in job['layout'].items():
                k = 'cpuLayout'
                r = 'cpuJobCnt'
                if job['nGpus'] > 0:
                    k = 'gpuLayout'
                    r = 'gpuJobCnt'
                cpu_ids = parseCpuList(l['cpu_ids'])
                data['nodes'][n][k].extend(cpu_ids)
                data['nodes'][n][r] += 1

        elif job['state'] == 'PENDING':
            # store future jobs with the nodes they're going to run on
            if job['startTime'] != 0 and job['schedNodes'] != None:
                b = pyslurm.hostlist()
                b.create(job['schedNodes'])
                for n in b.get_list():
                    n = str(n, 'utf-8')
                    #print(n,id)
                    data['nodes'][n]['futureJobs'].append(id)

    for hostname, node in data['nodes'].items():
        node['nCpuCores'] = len(node['cpuLayout'])
        node['nGpuCores'] = len(node['gpuLayout'])

    # bins of cores free
    bcu = {}
    u = {}
    for part, prefixes in partitions.items():
        # running/alloc, idle/avail, offline, blocked/unschedulable/inaccessible, total - for cores and nodes and gpus
        usage = { 'cores':{'a':0, 'i': 0, 'o': 0, 'b':0, 't':0},
                  'nodes':{'a':0, 'i': 0, 'o': 0, 'b':0, 't':0},
                   'gpus':{'a':0, 'i': 0, 'o': 0, 'b':0, 't':0} }
        bc = bins()

        for hostname, node in data['nodes'].items():
            for prefix in prefixes:
                if prefix in hostname:
                    # gpu jobs get 16 cores (in milan-gpu), but can use more
                    gpuCoresMax = max(partitionResGpuCores[part], node['nGpuCores'])
                    # cpu jobs get the rest. ie. max 48 on milan
                    cpuCoresMax = node['nCpus'] - gpuCoresMax 

                    # which type of cores we are considering
                    ty = 'nCpuCores'
                    tpc = 1
                    if part in partitionThreadsPerCore.keys():
                        tpc = partitionThreadsPerCore[part]
                    if 'gpu' in part:
                        ty = 'nGpuCores'
                        tpc = 1

                    nCpuIdleCores = cpuCoresMax - node['nCpuCores']*tpc
                    nGpuIdleCores = gpuCoresMax - node['nGpuCores']

                    # unavail nodes do not contribute to free counts
                    if node['avail']:
                        # can't schedule jobs on these cores for a variety of reasons
                        unsched = 0

                        if 'gpu' not in part:
                            # sstar, gstar, knl avail
                            if nCpuIdleCores > 0:
                                m = (node['realMem'] - node['allocMem'])/nCpuIdleCores
                                d = (node['realDisk'] - node['allocDisk'])/nCpuIdleCores

                                # cores/nodes can be unavail because of being out of ram or disk too
                                if d <= 100 or m <= 100:   # 100 MB per core
                                    unsched += nCpuIdleCores
                                    nCpuIdleCores = 0
                                    if debug:
                                        print('mem/disk blocked:', hostname, m, d)
                                else:
                                    mint = minFutureJobTime(node, data['jobs'], hostname, data['res'])
                                    if debug:
                                        print("hostname", hostname, "mint", mint)
                                    bc.add(nCpuIdleCores, m, d, mint, hostname)

                        # cores
                        usage['cores']['i'] += nCpuIdleCores
                        usage['cores']['t'] += cpuCoresMax
                        usage['cores']['b'] += unsched
                        usage['cores']['a'] += node[ty]*tpc

                        # nodes
                        if node[ty] == 0:
                            usage['nodes']['i'] += 1
                        else:
                            usage['nodes']['a'] += 1
                        usage['nodes']['t'] += 1

                        # gpus
                        # if there are any cores free then gpu jobs can run
                        if node['nCpus'] - node['nCpusUsed'] > 0:
                            usage['gpus']['i'] += node['nGpus'] - node['nGpusUsed']
                        else:
                            usage['gpus']['b'] += node['nGpus'] - node['nGpusUsed']   # blocked/unavail
                        usage['gpus']['a'] += node['nGpusUsed']
                        usage['gpus']['t'] += node['nGpus']

                    else:
                        # non-avail nodes - drained, draining, down, reserved (& unused)

                        # cores
                        if 'gpu' in part:
                            usage['cores']['o'] += nGpuIdleCores
                        else:
                            usage['cores']['o'] += nCpuIdleCores
                        usage['cores']['a'] += node[ty]*tpc
                        usage['cores']['t'] += node[ty]*tpc

                        # nodes
                        if node['nCpusUsed'] > 0:
                            usage['nodes']['a'] += 1
                        usage['nodes']['o'] += 1
                        usage['nodes']['t'] += 1

                        # gpus
                        usage['gpus']['o'] += node['nGpus'] - node['nGpusUsed']
                        usage['gpus']['a'] += node['nGpusUsed']
                        usage['gpus']['t'] += node['nGpusUsed']

        u[part] = usage
        bcu[part] = bc

    return u, bcu


def printVerbose(a, gpus="yup"):
    print('             ', end='')
    if gpus == 'first':
        for i in [ 'gpus', 'cores', 'nodes' ]:
            if i == "cores":
                print('   (  ', end='')
            print(i, 'a/i/o/b/t %d/%d/%d/%d/%d  ' % (a[i]['a'], a[i]['i'], a[i]['o'], a[i]['b'], a[i]['t']), end='')
            if i == "nodes":
                print(')', end='')
    else:
        for i in [ 'cores', 'nodes', 'gpus' ]:
            if i == "gpus" and gpus != "yup":
                continue
            print(i, 'a/i/o/b/t %d/%d/%d/%d/%d  ' % (a[i]['a'], a[i]['i'], a[i]['o'], a[i]['b'], a[i]['t']), end='')
    print('')

def secondsToStr(t):
    t = int(t - time.time())
    h = int(t/(3600))
    m = int((t - h*3600)/60)
    s = t - h*3600 - m*60
    return '%d:%.2d:%.2d' % ( h, m, s )

def uniq( list ):
    l = []
    prev = None
    for i in list:
        if i != prev:
            l.append( i )
        prev = i
    return l

# compress a list of integers into the minimal cexec-like list
def compressList(l):
    l = sorted(l)
    l = uniq(l)
    c = []
    start = -1
    end = -1
    for i in range(len(l)):
        if start == -1:
            start = l[i]
        if i == len(l)-1 or l[i]+1 != l[i+1]:
            c.append( (start, end) )
            start = -1
            end = -1
        else:
            end = l[i+1]

    s = ''
    last = len(c)-1
    for i, (start, end) in enumerate(c):
        if end == -1:
            s += '%d' % start
        else:
            s += '%d-%d' % ( start, end )
        if i != last:
            s += ','

    return s


def mysplit(s):
   head = s.rstrip('0123456789')
   tail = s[len(head):]
   return head, tail

def compact(l):
   c = {}
   for i in l:
      pre, n = mysplit(i)
      if pre not in c.keys():
         c[pre] = []
      c[pre].append(int(n))
   # sort
   cc = {}
   for i in c.keys():
      c[i].sort()
   return c

def toCexec(c):
   cc = ''
   for i in c.keys():
      if i in compactPrefixes.keys():
         cc += compactPrefixes[i] + ':'
      cc += compressList(c[i])
      cc += ' '
   return cc

def printFreeBins(b, n, lmp, ldp, printNodes=0, prefix=' '):
    cores = sorted(b.bins(), reverse=True)
    #print(cores)

    # compact output in the default view
    if printNodes == -1:  # -f forces full list
        printNodes = 0
    elif printNodes == 0 and len(cores) > 10:
        c = cores[:6]
        c.append('...')
        c.extend(cores[-2:])
        cores=c

    for i in cores:
        if i == '...':
            print(' '*20, '...')
            continue
        t='cores' 
        for j in n:  # list of whole nodes have this many cores
            if i == j:
               t='nodes'
               break

        if printNodes == 2:
            print('  cores %d' % i)
            print('    (mem MB/core, disk MB/core, time)')
            d = b.data[i]
            for k in range(len(d['nodes'])):
                t = d['time'][k]
                if t == None or (t - time.time()) > TMAX:
                    t = 'Inf'
                else:
                    t = secondsToStr(t)
                print(' '*10 + d['nodes'][k], '(%d,%d,%s)' % (int(d['mem'][k]), int(d['disk'][k]), t))
            continue

        lowMem=''
        if b.memsMedian(i) < lmp or b.memsAve(i) < lmp or b.memsMin(i) < 1:
            lowMem='(low memory jobs only)'
            if b.memsMax(i) < 10:
               lowMem='(zero memory jobs only)'
            elif b.memsMin(i) < 1:
               lowMem='(low/zero memory jobs only)'
        lowDisk=''
        if b.disksMedian(i) < ldp or b.disksAve(i) < ldp or b.disksMin(i) < 100:
            lowDisk='(low tmp disk jobs only)'
            if b.disksMax(i) < 200:
               lowDisk='(zero tmp disk jobs only)'
            elif b.disksMin(i) < 100:
               lowDisk='(low/zero tmp disk jobs only)'
        tmin = b.timesMin(i)
        tmax = b.timesMax(i)
        if tmin == None or (tmin - time.time()) > TMAX:
            ts = ''  # Inf time
        else:
            sm = secondsToStr(tmin)
            if tmax == None or (tmax - time.time()) > TMAX:
                sM = '    Inf'
            else:
                sM = secondsToStr(tmax)
            if sm == sM:
                ts = 'for %s             ' % sM
            else:
                ts = 'for %s to %s ' % (sm, sM)

        if printNodes == 1:
            detail=''
            if lowMem != '':
                detail += ' mem %d/%d/%d' % (int(b.memsMin(i)), int(b.memsAve(i)), int(b.memsMedian(i)))
            if lowDisk != '':
                detail += ' disk %d/%d/%d' % (int(b.disksMin(i)), int(b.disksAve(i)), int(b.disksMedian(i)))
            if detail != '':
                detail = ' --- free MB per core (min/ave/median):' + detail

        if t == 'nodes':   # whole nodes
            if b.cnt(i) == 1:
                t='node '
            print(prefix + '%3d %s (%d core) free' % (b.cnt(i), t, i), '(%d cores total)' % (i*b.cnt(i)), ts + lowMem + lowDisk)
            if printNodes == 1:
                print(prefix + '     ', toCexec(compact(b.nodes(i))) + detail)
        else:
            s='slots'
            if b.cnt(i) == 1:
                s='slot '
            print(prefix + '%3d %s for %d-core jobs free' % (b.cnt(i), s, i), '(%d cores total)' % (i*b.cnt(i)), ts + lowMem + lowDisk)
            if printNodes == 1:
                print(prefix + '     ', toCexec(compact(b.nodes(i))) + detail)

def usage(n):
    if n == 'qinfo':
        print("Usage: qinfo [-h] [-s|-v]")
        print("    Current node/core/gpu availability in each queue (partition).")
        print(" -v    Show more information.")
        print(" -s    Displayed in a format similar to 'sinfo -s'")
        print(" -h    this help")
    elif n == 'showbf':
        print("Usage: showbf [-h] [-f|-v|-vv]")
        print("   Show backfill information for each queue/partition.")
        print()
        print("   Jobs submitted with resource requests less than these backfill")
        print("   values should run immediately.")
        print("   eg.")
        print("      1 node  (32 core) free (32 cores total) for 1:10:16")
        print("   Means you can sbatch a 1 node, 32 core, 1 hour job and it should run now")
        print("   (allow ~5 mins for scheduling).")
        print()
        print("   This script includes some knowledge of resources constrainted due to")
        print("   queue partitioning, ram, local disk (tmp), etc. so is mostly accurate.")
        print("")
        print(" -f    full display of backfill slots")
        print("       the default is to try to fit in a reasonable number of lines.")
        print(" -v    show verbose output including node lists.")
        print(" -vv   even more verbose output.")
        print(" -h    this help.")
    elif n == 'spart':
        print("Usage: spart [-h] [-n]")
        print("   Show usage and backfill information for each queue/partition.")
        print(" -n    do not combine milan and milan-c into one partition")
        print(" -h    this help")
    else:
        print('no help available')
    sys.exit(0)

if __name__ == '__main__':
    # how are we being run
    n=sys.argv[0].split('/')[-1]

    if len(sys.argv) > 1:
        if sys.argv[1] in [ '-h', '--help', '-help' ]:
           usage(n)
        elif n == 'showbf' and ( sys.argv[1] != '-v' and sys.argv[1] != '-vv' and sys.argv[1] != '-f'):
            usage(n)
        elif n == 'qinfo' and ( sys.argv[1] != '-s' and sys.argv[1] != '-v' ):
            usage(n)
        elif n == 'spart' and ( sys.argv[1] != '-n' ):
            usage(n)

    # Get all data
    data = do_all()

    # find usage, and bcu (binned core usage) for each partition
    u, bcu = get_core_usage(data)

    # HACK HACK HACK
    # handle milan/milan-c/milan-gpu overlapping
    if 'milan' in ppp:
        # override ppp, cpu_ppp in spart -n mode in order to show milan-c separately from milan
        if n == 'spart' and len(sys.argv) > 1 and sys.argv[1] == '-n':
            # do not combine milan and milan-c
                ppp = [ "milan", "milan-c", "milan-gpu", "trevor" ]
                cpu_ppp = [ "milan", "milan-c", "trevor" ]

        # by default, combine milan and milan-c (the cpu components of the cluster) into just milan
        if 'milan-c' not in ppp:
            # usage
            for i in ['nodes', 'cores', 'gpus']:
                for j in [ 'a', 'i', 'o', 'b', 't' ]:
                    u['milan'][i][j] += u['milan-c'][i][j]
            del u['milan-c']
            # bins
            bcu['milan'].extend(bcu['milan-c'])
            del bcu['milan-c']

    if n == 'spart':
        for k in ppp:
            # percent avail/tot
            perc = {}
            for i in ['nodes', 'cores', 'gpus']:
                perc[i] = 0
                if u[k][i]['t'] > 0:
                    perc[i] = 100*u[k][i]['a']/u[k][i]['t']

            if k in cpu_ppp:
                print('%12s' % k, 'idle cores', u[k]['cores']['i'], 'used', str(int(perc['cores'])) + '%,',
                         'idle nodes', u[k]['nodes']['i'], 'used', str(int(perc['nodes'])) + '%,')
                printVerbose(u[k], gpus="nope")
            elif 'gpu' in k:
                print('%12s' % k, 'idle gpus', u[k]['gpus']['i'], 'used', str(int(perc['gpus'])) + '%',
                         '(used cores %d%% nodes %d%%)' % ( int(perc['cores']), int(perc['nodes']) ))
                printVerbose(u[k], gpus='first')
            else:
                print('%12s' % k, 'idle cores', u[k]['cores']['i'], 'used', str(int(perc['cores'])) + '%,',
                         'idle nodes', u[k]['nodes']['i'], 'used', str(int(perc['nodes'])) + '%,',
                         'idle gpus', u[k]['gpus']['i'], 'used', str(int(perc['gpus'])) + '%')
                printVerbose(u[k])

            printFreeBins(bcu[k], partitionMaxCpuCores[k], partitionLowMem[k], partitionLowDisk[k], False, ' '*16)

    elif n == 'qinfo':
        if len(sys.argv) > 1 and sys.argv[1] == '-s':
            # output a bit like sinfo -s
            s={}
            for k in ppp:
                for i in [ 'cores', 'nodes', 'gpus' ]:
                    d=u[k][i]
                    s[(k,i)]='%d/%d/%d/%d/%d' % (d['a'], d['i'], d['o'], d['b'], d['t'])

            # find max field lengths
            l = {}
            for i in [ 'cores', 'nodes', 'gpus' ]:
                l[i]=0
                for k in ppp:
                    l[i] = max(l[i], len(s[(k,i)]))
            #print(l)
            spc=2
            print('QUEUE     ' + ' '*(spc+max(0,l['nodes']-16))+'NODES(A/I/O/B/T)' + ' '*(spc+max(0,l['cores']-16)) + 'CORES(A/I/O/B/T)' + ' '*(spc+max(0,l['gpus']-15)) + 'GPUS(A/I/O/B/T)')
            for k in ppp:
                print(k + ' '*(13-len(k)), end='')
                for i in [ 'nodes', 'cores', 'gpus' ]:
                    fudge=0
                    if i == 'gpus' and 'gpu' not in k:
                        fudge=1
                    if 'gpu' not in k and i == 'gpus':
                        print(' '*(spc+fudge+int(l[i]/2)) + '-', end='')
                    elif 'gpu' in k and i == 'cores':
                        print(' '*(spc+fudge+l[i]-len(s[(k,i)])) + s[(k,i)]+ '+', end='')
                    else:
                        print(' '*(spc+fudge+l[i]-len(s[(k,i)])) + s[(k,i)], end='')
                print()
            print()
            print('  A/I/O/B/T = Allocated/Idle/Offline/Blocked/Total')
            print('     Blocked resources are those that are idle but unavailable')
            print('     due to resource requests from other jobs.')
            #print('     eg. node ram exhausted, no cpu cores available for a gpu job.')
            sys.exit(0)

        elif len(sys.argv) > 1 and sys.argv[1] == '-v':
            # eg.
            # QUEUE                  NODES                     CORES                      GPUS           
            #                  A   I   O   B   T         A    I    O    B    T        A   I   O   B   T
            # -----------------------------------------------------------------------------------------
            # skylake        114   3   0   0 117      3188  533    0  249 3744             -
            # skylake-gpu    116   1   0   0 117       227  241    0    0  468+     227   5   0   0 232
            # sstar           63  11  15   0  89       996  204  240    0 1200        0  19   6 106 125
            # gstar            3  47   4   0  54        44  572   88   24  640        0  94   9   0  94
            # knl              0   3   1   0   4         0  816  272    0  816             -

            cols = [ 'nodes', 'cores', 'gpus' ]
            colGap=4

            # find column widths for each section
            cw = {}
            for i in cols:
                cw[i] = 1
                for k in ppp:
                    d=u[k][i]
                    for j,v in d.items():
                        #print(j,v)
                        if v > 0:
                            cw[i] = max(cw[i], 2+int(math.log10(v)))
            cw['queue']=0
            pppp = [ "partition", "queue/" ]
            pppp.extend(ppp)
            for k in pppp:
                cw['queue'] = max(cw['queue'], len(k))
            #print(cw)
            print('QUEUE/' + (cw['queue']-len('QUEUE/')+colGap)*' ', end='')
            for i in cols:
                x = 5*cw[i] - len(i) + colGap
                y = x//2
                x = x - y
                if i == cols[-1]:
                   x = 0
                print(y*' ' + i.upper() + x*' ', end='')
            print() 
            print('PARTITION' + (cw['queue']-len('PARTITION')+colGap)*' ', end='')
            for i in cols:
                for j in [ 'A', 'I', 'O', 'B', 'T' ]:
                    print((cw[i]-1)*' ' + j, end='')
                if i != cols[-1]:
                    print(' '*colGap, end='')
            print()
            print((cw['queue']+colGap)*'-', end='')
            for i in cols:
                if i != cols[-1]:
                    print((5*cw[i]+colGap)*'-', end='')
                else:
                    print((5*cw[i])*'-', end='')
            print()
            for k in ppp:
                print(k + (cw['queue']-len(k)+colGap)*' ', end='')
                for i in cols:
                    if 'gpu' not in k and i == 'gpus':
                        print(' '*(colGap+int(cw[i]/2)) + '-', end='')
                    else:
                        for j in [ 'a', 'i', 'o', 'b', 't' ]:
                            print('{num:{field_size}d}'.format(num=u[k][i][j], field_size=(cw[i])), end='')
                    if i != cols[-1]:
                        print(' '*colGap, end='')
                print()
            print()
            print('  A/I/O/B/T = Allocated/Idle/Offline/Blocked/Total')
            print('     Blocked resources are those that are idle but unavailable')
            print('     due to resource requests from other jobs.')
            sys.exit(0)

        elif len(sys.argv) > 1:
            usage(n)

        # short version
        print('               Idle/Available')
        print('Partition    Nodes  Cores   Gpus')
        for k in ppp:
            print(k + ' '*(11-len(k)), end='')
            for i in [ 'nodes', 'cores', 'gpus' ]:
                d=u[k][i]
                if 'gpu' not in k and i == 'gpus':
                    print('      -', end='')
                else:
                    print('%7d' % d['i'], end='')
            print()

    elif n == 'showbf':
        printNodes=0
        if len(sys.argv) > 1 and sys.argv[1] == '-f':
            printNodes=-1
        elif len(sys.argv) > 1 and sys.argv[1] == '-v':
            printNodes=1
        elif len(sys.argv) > 1 and sys.argv[1] == '-vv':
            printNodes=2

        for k in cpu_ppp:
            print(k)
            printFreeBins(bcu[k], partitionMaxCpuCores[k], partitionLowMem[k], partitionLowDisk[k], printNodes)

    sys.exit(0)
